repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.7.0
    hooks:
      - id: aoc-tiles
        args:
          - --auto-add-tiles-to-git=amend
          - --theme=aoc
          - --animation=snow
          - --create-all-days
          - --overwrite-year
          - --day-pattern="(?<!\d)([012]?\d)(?!\d)"
          - --exclude-patterns='*.txt'