repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.7.0
    hooks:
      - id: aoc-tiles
        args:
          - --auto-add-tiles-to-git=amend- --theme=aoc --animation=snow --overwrite-year=2025 --exclude-patterns='*.txt' --count-as-solved-when=on_leaderboard --verbosity=2 --what-to-show-on-right-side=checkmark
         